apiVersion: v1
kind: Service
metadata:
  name: dispatch
  labels:
    app: dispatch
    shop.io/team: logistics
spec:
  selector:
    app: dispatch
  ports:
    - name: http
      port: 8108
      targetPort: 8108
