apiVersion: v1
kind: Service
metadata:
  name: location-gateway
  labels:
    app: location-gateway
    shop.io/team: location
spec:
  selector:
    app: location-gateway
  ports:
    - name: http
      port: 8109
      targetPort: 8109
