apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
    shop.io/team: marketplace
spec:
  selector:
    app: order
  ports:
    - name: http
      port: 8105
      targetPort: 8105
