apiVersion: v1
kind: Service
metadata:
  name: ranking
  labels:
    app: ranking
    shop.io/team: discovery
spec:
  selector:
    app: ranking
  ports:
    - name: http
      port: 8115
      targetPort: 8115
